### ISSUE TITLE
[chat] bugs :sos: 

### ISSUE THREAD

**Issue by tsiguenz** [tsiguenz/ft_transcendence#125]
# First bug

 - Create a private message with another user
 - Post a message
 - Delete the account
 - Then the other user still got an error when going to the chat

# Second bug

- Join a room with 2 users (general for me)
- Post a message
- Delete the account
- Signup with the same nickname than the user deleted
- Go to the chat and see some magic

Tell me if you want screen recording or some details.

**Comment by Crysicia** [comment]
WIll look into it tomorrow

**Comment by Crysicia** [comment]
@tsiguenz can I get a screen capture of the second bug ? I can't reproduce...
The issue appears to be with the stores being persisted tho...

**Comment by tsiguenz** [comment]
> @tsiguenz can I get a screen capture of the second bug ? I can't reproduce... The issue appears to be with the stores being persisted tho...

Look like store is not cleared when we delete account.

https://github.com/tsiguenz/ft_transcendence/assets/43640980/01c9fd3b-2dee-46cd-8021-e125f4b45dfb

**Comment by Crysicia** [comment]
I'm on it!
