### ISSUE TITLE
Chatroom never delete ?

### ISSUE THREAD

**Issue by gmorange42** [tsiguenz/ft_transcendence#137]
If everyone leave a chatroom, it's not delete because we can't create a new chatroom with the same name. ex: i create a chatroom 'test', i leave it, i can't create a new chatrrom called 'test'.

**Comment by tsiguenz** [comment]
> If a everyone leave a chatroom, it's not delete because we can't create a new chatroom with the same name. ex: i create a chatroom 'test', a leave it, a can't create a new chatrrom called 'test'.

It's not a bug. Chatroom can exist without users but for Private Message I think it's a bug
